DROP TABLE Invoice
CREATE TABLE [dbo].[Invoice] (
    [Invoice no]        INT           NOT NULL,
    [Invoice Date]      DATE          NOT NULL,
	[Terms]             VARCHAR (50)  NULL,
    [Pay Due date]      DATE          NOT NULL,
    [PO number]         VARCHAR (50)  NULL,
    [Category]          VARCHAR (50)  NULL,
	[Custom1] TEXT,
	[Custom2] TEXT,
	[Qty] INT,
	[Item] TEXT,
	[Description] TEXT,
	[Prim Tax] FLOAT,
	[Sec Tax] FLOAT,
	[Discount] FLOAT,
	[Cost] FLOAT,
	[Extended Cost] FLOAT,
	[Invoice Notes] TEXT,
	[Internl Notes] TEXT,
    [Ship cost]         FLOAT (53)    NOT NULL,
    [Tax1]              FLOAT (53)    NOT NULL,
    [Tax2]              FLOAT (53)    NULL,
    [Total cost]        FLOAT (53)    NULL,
    [Payments received] FLOAT (53)    NULL,
    [Customer]          VARCHAR (50)  NULL,
    [Notes]             VARCHAR (MAX) NULL,
    [Status]            VARCHAR (50)  NULL,
    [Location]          VARCHAR (50)  NOT NULL,
	[Billing Contact] VARCHAR (50),
	[Shipping Contact] VARCHAR(50),
    PRIMARY KEY CLUSTERED ([Invoice no] ASC)
);

